name: "DevSecOps Pipeline"
on: [push, pull_request]

env:
  NODE_VERSION: 20
  TRUFFLEHOG_VERSION: v3.64.0  # Pin version untuk security

jobs:
  build:
    name: "🏗️ Build & Install"
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outputs.status }}
    steps:
      - name: "🔁 Checkout Code"
        uses: actions/checkout@v4
        
      - name: "⎔ Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: "📦 Install Dependencies"
        run : npm install --ignore-scripts

  sast:
    name: "🔍 SAST Analysis"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  # Specify the languages you want to analyze

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: codeql-results.sarif  # Example output file name

  secret_scanning:
    name: "🔑 Secret Scanning"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TruffleHog
        run: |
          docker run --rm -v $(pwd):/repo trufflesecurity/trufflehog filesystem /repo --json --github-actions > trufflehog-results.json

      - name: Upload TruffleHog Results
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog-results.json

  build_and_push:
    name: "🐳 Build and Push Image"
    runs-on: ubuntu-latest
    #needs: [sast, secret_scanning]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear gcloud config
        run: gcloud config configurations delete default --quiet || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Gunakan SA key dari GitHub Secrets

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: latest  # Optional, specify version if needed

      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t "asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops-repo/juice-shop:${{ github.run_id }}" .

      - name: Push Docker Image
        run: |
          docker push "asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops-repo/juice-shop:${{ github.run_id }}"
          docker tag "asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops-repo/juice-shop:${{ github.run_id }}" asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops-repo/juice-shop:latest
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/devsecops-repo/juice-shop:latest

  container_scanning:
    name: "🔍 Container Scanning"
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear gcloud config
        run: gcloud config configurations delete default --quiet || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Gunakan SA key dari GitHub Secrets

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: latest  # Optional, specify version if needed

      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Run Trivy
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd):/repo \
            -v $HOME/.config/gcloud:/root/.config/gcloud \  # Mount GCP credentials
            aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL \
            asia-southeast2-docker.pkg.dev/syafiq-devsecops-playground/devsecops-repo/juice-shop:13023406990

  notify:
    name: "📢 Notification"
    needs: [container_scanning]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "📤 Send Results to Defect Dojo"
        run: echo "Implement Defect Dojo integration"  # Temporary placeholder